pull_request_rules:
  - name: merge when green
    conditions:
      - "label=⤴️PR: Merge When Green"
      - "label!=⤴️PR: Work In Progress"
      - "label!=⤴️PR: Can't Be Automerged"
    actions:
      merge:
        method: merge
  - name: label style updates
    conditions:
      - author=restyled-io
    actions:
      label:
        add: 
          - "⤴️PR: Style Update"
          - "⤴️PR: Enhancement"
          - "⤴️PR: Merge When Green"
