version: 3

pullapprove_conditions:
- "base.ref == 'master'"
  unmet_status: success
  explanation: "Minion3665 wishes you luck. This pr will not need reviews to pass 😊"
- condition: "'⤴️PR: Work In Progress' in labels"
  unmet_status: pending
  explanation: "Work in progress"
- condition:
  - >
    "'Travis CI - Pull Request' in statuses.successful" and
    "'AnyLint' in statuses.successful" and
    "'restyled' in statuses.successful" and
    "'task-list-completed' in statuses.successful" and
  unmet_status: pending
  explanation: "Tests must pass before review starts"

groups:
  protected:
    conditions:
    - >
      '*.md' in files or
      '*.html' in files or
      '*.yml' in files or
      '*.yaml' in files or
      '*.json' in files or
      'CNAME' in files or
      'config.js' in files or
      'index.js' in files or
      'webpack.config.js' in files or
      '*favicon*' in files
    reviewers:
      users:
      - Minion3665
    reviews:
      required: 1
      request: 1
