version: 3

pullapprove_conditions:
- condition: "body and '- [ ]' not in body"
  unmet_status: pending
  explanation: "Work in progress (From incomplete task list)"
- condition: "'⤴️PR: Work In Progress' not in labels"
  unmet_status: pending
  explanation: "Work in progress (From label)"
- "base.ref == 'master'"
- condition: "'*restyled*' in statuses.successful"
  unmet_status: pending
  explanation: "Your style must fit before reviewing starts"
- condition: "'*AnyLint*' in statuses.successful"
  unmet_status: pending
  explanation: "AnyLint must succeed before reviewing starts"
- condition: "'*Travis CI - Pull Request*' in statuses.successful"
  unmet_status: pending
  explanation: "The Travis-CI Build must pass before reviewing starts"

groups:
  protected:
    conditions:
    - >
      '*.md' in files or
      '*.html' in files or
      '*.yml' in files or
      '*.yaml' in files or
      '*.json' in files or
      'CNAME' in files or
      'config.js' in files or
      'index.js' in files or
      'webpack.config.js' in files or
      '*favicon*' in files
    reviewers:
      users:
      - Minion3665
      teams:
      - beta-maintainers
    reviews:
      required: 2
      request: 1
      request_order: random
      author_value: 1
