language: node_js
node_js:
  - "node"

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GH_TOKEN
  target_branch: gh_pages
  on:
    branch: master
